# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
